apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.fullname" . }}-config
  namespace: {{ include "agent.namespace" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
