{{- if and .Values.workflows.enabled (not .Values.workflows.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}-workflows
  namespace: {{ include "agent.namespace" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.workflows.files }}
data:
  {{- range $key, $value := .Values.workflows.files }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- else }}
data: {}
{{- end }}
{{- end }}
